name: Go
on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: dependencies
        run: go mod download
      
      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./... -run "Unit"